version: "3.9"

services:
  nginx:
    build: .
    image: heartexlabs/label-studio:latest
    ports:
      - "8080:8085"
      - "8081:8086"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
#   Optional: Specify SSL termination certificate & key
#   Just drop your cert.pem and cert.key into folder 'deploy/nginx/certs'
#      - NGINX_SSL_CERT=/certs/cert.pem
#      - NGINX_SSL_CERT_KEY=/certs/cert.key
    volumes:
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/certs:/certs:ro
#   Optional: Override nginx default conf
#      - ./deploy/nginx/default.conf:/label-studio/deploy/nginx/default.conf
    command: nginx

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    expose:
      - "8000"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=labelstudio
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=${DB_PASSWD}
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=labelstudio-db.caqqxzhptzmg.us-east-1.rds.amazonaws.com
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
      - LOG_LEVEL=DEBUG
      - LABEL_STUDIO_COPY_STATIC_DATA=true
      - LABEL_STUDIO_ALLOW_ORGANIZATION_WEBHOOKS=true
    volumes:
      - ./mydata:/label-studio/data:rw
    command: label-studio-uwsgi

volumes:
  static: {}
